# Generated by Django 3.2.9 on 2021-11-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_name', models.CharField(max_length=30)),
                ('si_name', models.CharField(max_length=30)),
                ('gu_name', models.CharField(max_length=30)),
                ('dong_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BilliardClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateTimeField()),
                ('club_name', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.address')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.billiardclub')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rating', models.IntegerField(default=1000)),
                ('age', models.IntegerField(default=0)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.address')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_date', models.DateTimeField()),
                ('average_rating', models.IntegerField()),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.competition')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='player.player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionToGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.competition')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.game')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.player'),
        ),
    ]
