# Generated by Django 3.2.9 on 2021-12-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billiardclub',
            old_name='club_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='competition',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
