# Generated by Django 3.2.9 on 2021-12-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20211201_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='average_rating',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='CompetitionToGame',
        ),
    ]
