# Generated by Django 3.2.9 on 2021-12-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20211201_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.competition'),
        ),
    ]
