# Generated by Django 3.2.9 on 2021-12-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_alter_game_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
